# Generated by Django 5.2.17 on 2026-08-17 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0005_technicalsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='LONG', max_length=5)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('STOPPED', 'Stopped out'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=10)),
                ('entry_at', models.DateTimeField()),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('quantity', models.PositiveIntegerField()),
                ('stop_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('target_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('exit_at', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('setup_name', models.CharField(blank=True, max_length=120)),
                ('setup_tags', models.CharField(blank=True, max_length=300)),
                ('thesis', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='market.symbol')),
            ],
            options={
                'ordering': ['-entry_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TradeSetupSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('data_as_of_date', models.DateField(blank=True, null=True)),
                ('technicals', models.JSONField(default=dict)),
                ('recent_bars', models.JSONField(default=dict)),
                ('entry_quality', models.JSONField(default=dict)),
                ('screener_context', models.JSONField(default=dict)),
                ('calculation_versions', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(editable=False, max_length=64)),
                ('chart_image', models.FileField(blank=True, upload_to='trade_snapshots/%Y/%m/')),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_snapshot', to='trading.trade')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['status', '-entry_at'], name='trade_status_entry_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['symbol', '-entry_at'], name='trade_symbol_entry_idx'),
        ),
    ]
