# Generated by Django 5.2.17 on 2026-08-15 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1)),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=6, max_digits=20)),
                ('high', models.DecimalField(decimal_places=6, max_digits=20)),
                ('low', models.DecimalField(decimal_places=6, max_digits=20)),
                ('close', models.DecimalField(decimal_places=6, max_digits=20)),
                ('adj_close', models.DecimalField(decimal_places=6, max_digits=20)),
                ('volume', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlcv', to='market.symbol')),
            ],
            options={
                'ordering': ['symbol', 'timeframe', 'date'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', '-date'], name='ohlcv_symbol_tf_date_idx'), models.Index(fields=['timeframe', '-date'], name='ohlcv_tf_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'timeframe', 'date'), name='unique_symbol_timeframe_date')],
            },
        ),
    ]
