# Generated by Django 5.2.17 on 2026-08-16 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_ohlcv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=10)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('market', models.CharField(choices=[('US', 'United States'), ('IND', 'India')], max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('definition', models.TextField(blank=True)),
                ('is_ohlcv_enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['market', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UniverseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnresolvedUniverseSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universe_code', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='symbol',
            options={'ordering': ['market', 'symbol']},
        ),
        migrations.AddField(
            model_name='symbol',
            name='index_membership',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='ipo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='market',
            field=models.CharField(choices=[('US', 'United States'), ('IND', 'India')], default='US', max_length=3),
        ),
        migrations.AddField(
            model_name='symbol',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='market_cap_category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['market', 'is_active'], name='symbol_market_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='symbol',
            constraint=models.UniqueConstraint(fields=('market', 'exchange', 'symbol'), name='unique_market_exchange_symbol'),
        ),
        migrations.AddField(
            model_name='universemembership',
            name='import_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='market.importbatch'),
        ),
        migrations.AddField(
            model_name='universemembership',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universe_memberships', to='market.symbol'),
        ),
        migrations.AddField(
            model_name='universemembership',
            name='universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='market.universe'),
        ),
        migrations.AddField(
            model_name='unresolveduniversesymbol',
            name='import_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unresolved_symbols', to='market.importbatch'),
        ),
        migrations.AddIndex(
            model_name='universemembership',
            index=models.Index(fields=['universe', 'effective_to'], name='universe_current_members_idx'),
        ),
        migrations.AddConstraint(
            model_name='universemembership',
            constraint=models.UniqueConstraint(fields=('universe', 'symbol', 'effective_from'), name='unique_universe_symbol_effective_from'),
        ),
        migrations.AddConstraint(
            model_name='unresolveduniversesymbol',
            constraint=models.UniqueConstraint(fields=('import_batch', 'universe_code', 'symbol'), name='unique_unresolved_symbol_per_batch'),
        ),
    ]
