# Generated by Django 5.2.17 on 2026-08-16 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_importbatch_universe_universemembership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHLCVIngestionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='yahoo', max_length=30)),
                ('timeframe', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default='D', max_length=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_bar_date', models.DateField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_states', to='market.symbol')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'last_attempt_at'], name='ingest_status_attempt_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'provider', 'timeframe'), name='unique_symbol_provider_timeframe_state')],
            },
        ),
    ]
