# Generated by Django 5.2.17 on 2026-08-17 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_ohlcvingestionstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1)),
                ('as_of_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('sma20', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('sma50', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('sma100', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('sma150', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('sma250', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('atr14', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('atr_pct', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('adr20', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('adr_pct', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('macd', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('macd_signal', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('momentum', models.CharField(blank=True, max_length=8)),
                ('vwap', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('vwap_status', models.CharField(blank=True, max_length=8)),
                ('adx14', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('trending', models.BooleanField(null=True)),
                ('dmi_plus14', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('dmi_minus14', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('dmi_status', models.CharField(blank=True, max_length=8)),
                ('rsi14', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('rsi_status', models.CharField(blank=True, max_length=12)),
                ('bb20_upper', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('bb20_middle', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('bb20_lower', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('bb20_width', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('kc20_upper', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('kc20_middle', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('kc20_lower', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('kc20_width', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('bb_kc_ratio', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('is_squeeze', models.BooleanField(null=True)),
                ('calculation_version', models.CharField(default='v1', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_snapshots', to='market.symbol')),
            ],
            options={
                'indexes': [models.Index(fields=['timeframe', 'as_of_date'], name='technical_tf_date_idx'), models.Index(fields=['timeframe', 'momentum'], name='technical_tf_momentum_idx'), models.Index(fields=['timeframe', 'is_squeeze'], name='technical_tf_squeeze_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'timeframe'), name='unique_symbol_timeframe_technical')],
            },
        ),
    ]
