# Generated by Django 5.2.17 on 2026-08-17 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_technicalsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_type', models.CharField(choices=[('HORIZONTAL', 'Horizontal level'), ('TREND_RAY', 'Trend ray'), ('PARALLEL_CHANNEL', 'Parallel channel')], max_length=20)),
                ('source_timeframe', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1)),
                ('points', models.JSONField(default=list)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(default='#7f56d9', max_length=20)),
                ('line_width', models.PositiveSmallIntegerField(default=2)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_drawings', to='market.symbol')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['symbol', 'is_visible'], name='drawing_symbol_visible_idx')],
            },
        ),
    ]
